# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='work',
            name='feeling',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_category',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_type',
        ),
        migrations.AddField(
            model_name='work',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
