# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_auto_20170302_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
